<a href="https://colab.research.google.com/github/kush551/Starting-With-ML/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.1.0+cu121


In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [7]:
vector = torch.tensor([7 ,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [17]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim

2

In [16]:
MATRIX[2]

tensor([10,  5])

In [18]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,7],
                        [8,9,10]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 3,  6,  7],
        [ 8,  9, 10]])

### Random Tensor

In [ ]:
# Creat a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4956, 0.4793, 0.7775, 0.2880],
        [0.2244, 0.0897, 0.6299, 0.1226],
        [0.6775, 0.3376, 0.2990, 0.2674]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#Creat a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 244, 244)) #colour channels,height,width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

#zero and ones

In [ ]:
# creating a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#creat a tensor of ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Creating a range of tensor and tensor-like

In [ ]:
#use torh.range()
one_to_ten=torch.arange(start=1, end=11, step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating tesors like
ten_zero=torch.zeros_like(input=one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor datatypes (Important and hard)

In [ ]:
#Float 32 tenosr
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
#create a tensor
some_tensor= torch.rand(3, 4)

some_tensor

tensor([[0.2812, 0.0217, 0.3378, 0.5554],
        [0.3778, 0.0033, 0.9366, 0.2925],
        [0.1103, 0.7386, 0.7826, 0.5162]])

In [ ]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor; {some_tensor.shape}")
print(f"Device tesnor in on: {some_tensor.device}")

tensor([[0.2812, 0.0217, 0.3378, 0.5554],
        [0.3778, 0.0033, 0.9366, 0.2925],
        [0.1103, 0.7386, 0.7826, 0.5162]])
Datatype of tensor: torch.float32
Shape of tensor; torch.Size([3, 4])
Device tesnor in on: cpu


Manipulating Tesors(tensor operation)

In [ ]:
#creating a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
#Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor, 10)


tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

from os import WIFSTOPPED
### Matrix Multiplication

Two ways to multiply

1. element wise
2. matrix wise(dot product)

In [ ]:
#Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [ ]:
#Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

### finding the min,max,mean,sum,etc(tensor aggriation)

In [ ]:
#create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
#findint the max
torch.max(x), x.max()


(tensor(90), tensor(90))

In [ ]:
#find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
#find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

### Finding the position min and max


In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#Find the position in tensor that has the minimum value with argmiin
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
#Find the position in tensor that has the maximum value with argmax
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

In [ ]:
#Reshaping, stacking, squeezing and unsquesszing tensor


In [ ]:
# creating a tensor
import torch
x = torch.arange (1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#add an extra dimension
x_reshaped = x.reshape((1, 9))
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Changing the view
z= x.view (1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#stack tensor on top of each other
x_stack = torch.stack([x ,x ,x ,x ], dim=0)
x_stack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specif

x_original = torch.rand(size=(224,224,3))#[Height, width, Colour channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shift axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]



Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0] = 728218
x_original[0 ,0 ,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

### Indexing (Selecting Data from tensor)


In [ ]:
import torch
x=torch.arange(1, 10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# indexed on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
#index on thr most inner bracket(last braket)
x[0][2][2]

tensor(9)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
#get all value of the 0 simensoion byt only the 1 index of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]


tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])


tensor(9)
tensor([[3, 6, 9]])


###Pyorch tensor & NumPy


In [ ]:
#NumPy array to torch
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array = array +1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### reproducblty

In [ ]:
import torch
random_tensor_A= torch.rand(3, 4)
random_tensor_B= torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7198, 0.7938, 0.9638, 0.4299],
        [0.8338, 0.2996, 0.9140, 0.5912],
        [0.2971, 0.5242, 0.7327, 0.3396]])
tensor([[0.2657, 0.9431, 0.4100, 0.1222],
        [0.5721, 0.1024, 0.5333, 0.0791],
        [0.2736, 0.4115, 0.5497, 0.4919]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
import torch
#lets make some random but reproducible tensor
RANDOM_SEED = 55
torch.manual_seed(RANDOM_SEED)
random_tensor_C= torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D= torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8357, 0.9378, 0.7439, 0.5674],
        [0.8682, 0.4765, 0.0858, 0.7740],
        [0.9677, 0.1874, 0.0993, 0.0611]])
tensor([[0.8357, 0.9378, 0.7439, 0.5674],
        [0.8682, 0.4765, 0.0858, 0.7740],
        [0.9677, 0.1874, 0.0993, 0.0611]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensor and Pytorch on the GPUs

In [ ]:
!nvidia-smi

Sun Jan 21 17:55:35 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### check for GPU access with PyTorch

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
device ="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1