<a href="https://colab.research.google.com/github/kush551/Starting-With-ML/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.1.0+cu121


In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7 ,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,7],
                        [8,9,10]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 3,  6,  7],
        [ 8,  9, 10]])

### Random Tensor

In [ ]:
# Creat a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2216, 0.5651, 0.2251, 0.4383],
        [0.3527, 0.9575, 0.4397, 0.8276],
        [0.9143, 0.9597, 0.3267, 0.7595]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#Creat a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 244, 244)) #colour channels,height,width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 244, 244]), 3)

#zero and ones

In [ ]:
# creating a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#creat a tensor of ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Creating a range of tensor and tensor-like

In [ ]:
#use torh.range()
one_to_ten=torch.arange(start=1, end=11, step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating tesors like
ten_zero=torch.zeros_like(input=one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor datatypes (Important and hard)

In [ ]:
#Float 32 tenosr
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
#create a tensor
some_tensor= torch.rand(3, 4)

some_tensor

tensor([[0.1467, 0.3683, 0.9964, 0.6920],
        [0.7921, 0.2188, 0.6412, 0.4472],
        [0.8989, 0.8726, 0.6891, 0.7681]])

In [ ]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor; {some_tensor.shape}")
print(f"Device tesnor in on: {some_tensor.device}")

tensor([[0.1467, 0.3683, 0.9964, 0.6920],
        [0.7921, 0.2188, 0.6412, 0.4472],
        [0.8989, 0.8726, 0.6891, 0.7681]])
Datatype of tensor: torch.float32
Shape of tensor; torch.Size([3, 4])
Device tesnor in on: cpu


Manipulating Tesors(tensor operation)

In [ ]:
#creating a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
#Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor, 10)


tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])